# Generated by Django 4.1.5 on 2023-01-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_products_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
