# Generated by Django 4.1.5 on 2023-01-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='first_name',
        ),
    ]
