# Generated by Django 4.1.5 on 2023-05-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_myuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='images',
        ),
    ]
