# Generated by Django 4.1.5 on 2023-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_image_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
