# Generated by Django 4.1.5 on 2023-06-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_products_img_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images',
            new_name='image',
        ),
    ]
